PROJECT_NAME: PracticalML
EXPERIMENT: cap_svt_charades_s224_f8_exp_32_train
OUTPUT_DIR: ./runs
WANDB_KEY: 547d969d74fa2db0a0eb6a8b49490f5fddccfc04
SEED: 42

MODEL:
  TYPE: captioning
  ENCODER:
    TYPE: VideoTransformer
    PRETRAINED: checkpoints/kinetics400_vitb_ssl.pth
    HIDDEN_SIZE: 768
    RETURN_ALL_HIDDEN: False

  HEAD:
    TYPE: Generative
    LANGUAGE_MODEL: gpt2
    MAX_TOKENS: 128

  LOSS: CrossEntropyLoss

DATA:
  DATASET: charades_caption
  ROOT_PATH: data/raw/Charades
  TRAIN_CSV: Charades_per-frame_annotations_fps1.5_captioning_train.csv
  TEST_CSV: Charades_per-frame_annotations_fps1.5_captioning_test.csv
  IMG_SIZE: 224
  NUM_SAMPLED_FRAMES: 8
  NUM_SAMPLED_FRAMES_MULT: 4
  CLIP_DURATION: 30
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  NUM_WORKERS: 16
  FRAME_SKIP: 2

TRAIN:
  FREEZE_ENCODER: True
  NUM_EPOCHS: 20
  BATCH_SIZE: 4
  OPTIM:
    TYPE: AdamW
    INIT_LEARNING_RATE: 0.0002
    MIN_LEARNING_RATE: 0.000001
    EPS: 0.000001
    BETAS: [0.9, 0.999]
    LR_MILESTONES: [18]
  LOG_STEPS: 50
  ACCELERATOR: auto
  DEVICES: auto
  PRECISION: 32
  BEST_CHECKPOINT_BY: val_loss
  COMPUTE_METRIC_AT_TRAIN_TIME: False
