PROJECT_NAME: PracticalML
EXPERIMENT: cap_svt_charades_s224_f8_exp0
OUTPUT_DIR: ./runs
WANDB_KEY: 547d969d74fa2db0a0eb6a8b49490f5fddccfc04
SEED: 42

MODEL:
  TYPE: captioning
  ENCODER:
    TYPE: VideoTransformer
    PRETRAINED: checkpoints/kinetics400_vitb_ssl.pth
    HIDDEN_SIZE: 768
    RETURN_ALL_HIDDEN: False

  HEAD:
    TYPE: Generative
    LANGUAGE_MODEL: distilgpt2
    MAX_TOKENS: 128

DATA:
  DATASET: charades_caption
  ROOT_PATH: data/processed/Charades
  TRAIN_CSV: Charades_v1_train_perframe_cap_ann.csv
  VAL_CSV: Charades_v1_test_perframe_cap_ann.csv
  TRAIN_CROP_SIZE: 224
  NUM_SAMPLED_FRAMES: 8
  # SAMPLE_RATE: 4
  # FPS: 30
  CLIP_DURATION: 47
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  NUM_WORKERS: 8

TRAIN:
  FREEZE_ENCODER: True
  NUM_EPOCHS: 30
  BATCH_SIZE: 4
  OPTIM:
    TYPE: AdamW
    INIT_LEARNING_RATE: 0.00005
    MIN_LEARNING_RATE: 0.000001
    EPS: 0.000001
    BETAS: [0.9, 0.999]
    MAX_LR_STEPS: 100
  LOG_STEPS: 50
  ACCELERATOR: gpu
  DEVICES: 1
