PROJECT_NAME: PracticalML

MODEL:
  TYPE: classification
  ENCODER:
    TYPE: VideoTransformer
    PRETRAINED: checkpoints/kinetics400_vitb_ssl.pth
    HIDDEN_SIZE: 768
    RETURN_ALL_HIDDEN: False

  HEAD:
    TYPE: MLP
    LAYERS: [128,128]
    NUM_CLASSES: 10

DATA:
  DATASET: ucf101
  ROOT_PATH: data/raw/UCF101_subset
  TRAIN_CROP_SIZE: 224
  NUM_SAMPLED_FRAMES: 8
  SAMPLE_RATE: 4
  FPS: 30
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  NUM_WORKERS: 0

TRAIN:
  FREEZE_ENCODER: True
  NUM_EPOCHS: 10
  BATCH_SIZE: 1
  OPTIM:
    TYPE: AdamW
    INIT_LEARNING_RATE: 0.0001
    MIN_LEARNING_RATE: 0.000001
    EPS: 0.000001
    BETAS: [0.9, 0.999]
    MAX_LR_STEPS: 100
  LOG_STEPS: 50
  ACCELERATOR: cpu
  DEVICES: 1
  COMET_KEY: zR96oNVqYeTUXArmgZBc7J9Jp
  
OUTPUT_DIR: runs/cls_svt_s224_f8_exp0