PROJECT_NAME: PracticalML
EXPERIMENT: cls_svt_ucf101_s224_f8_exp0
OUTPUT_DIR: ./runs
WANDB_KEY: 547d969d74fa2db0a0eb6a8b49490f5fddccfc04
SEED: 42

MODEL:
  TYPE: classification
  ENCODER:
    TYPE: VideoTransformer
    PRETRAINED: checkpoints/kinetics400_vitb_ssl.pth
    HIDDEN_SIZE: 768
    RETURN_ALL_HIDDEN: False

  HEAD:
    TYPE: MLP
    LAYERS: [128,128]
    NUM_CLASSES: 10
    MULTI_LABEL: False

  LOSS: CrossEntropyLoss

DATA:
  DATASET: ucf101
  ROOT_PATH: data/raw/UCF101_subset
  IMG_SIZE: 224
  NUM_SAMPLED_FRAMES: 8
  CLIP_DURATION: 1.067
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  NUM_WORKERS: 4

TRAIN:
  FREEZE_ENCODER: True
  NUM_EPOCHS: 10
  BATCH_SIZE: 8
  OPTIM:
    TYPE: AdamW
    INIT_LEARNING_RATE: 0.0001
    MIN_LEARNING_RATE: 0.000001
    EPS: 0.000001
    BETAS: [0.9, 0.999]
    MAX_LR_STEPS: 100
  LOG_STEPS: 50
  ACCELERATOR: auto
  DEVICES: auto
  PRECISION: 16
  BEST_CHECKPOINT_BY: val_accuracy
  COMPUTE_METRIC_AT_TRAIN_TIME: True