PROJECT_NAME: PracticalML
EXPERIMENT: cls_svt_charades_s224_f8_exp8
OUTPUT_DIR: ./runs
WANDB_KEY: 547d969d74fa2db0a0eb6a8b49490f5fddccfc04
SEED: 42

MODEL:
  TYPE: classification
  ENCODER:
    TYPE: VideoTransformer
    PRETRAINED: checkpoints/kinetics400_vitb_ssl.pth
    HIDDEN_SIZE: 768
    RETURN_ALL_HIDDEN: False
    NUM_VISUAL_TOKENS: 1

  HEAD:
    TYPE: MLP
    REDUCER_TYPE: token_wise # Options: token_wise, hidden_wise. If RETURN_ALL_HIDDEN is False, this is ignored.
    LAYERS: [512, 512]
    DROPOUT: 0.7  # Optional: Dropout probability
    LAYER_NORM: False  # Optional: Use layer normalization
    NUM_CLASSES: 157
    MULTI_LABEL: True
    THRESHOLD: 0.5

  LOSS: BCEWithLogitsLoss
  USE_CLASS_WEIGHTS: True # 2

DATA:
  ENCODING_DIR: data/encodings/cls_svt_charades/ # path to precomputed hidden states from the encoder
  DATASET: charades_action_classification
  ROOT_PATH: data/raw/Charades
  TRAIN_CSV: Charades_per-frame_annotations_fps1.5_action_cls_train.csv
  TEST_CSV: Charades_per-frame_annotations_fps1.5_action_cls_test.csv
  IMG_SIZE: 224
  NUM_SAMPLED_FRAMES: 8
  FPS: 1.5
  CLIP_DURATION: 6 # we want about 8 frames, fps = 1.5 -> set clip duration to 6s
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  NUM_WORKERS: 16

TRAIN:
  FREEZE_ENCODER: True
  NUM_EPOCHS: 300
  BATCH_SIZE: 8
  OPTIM:
    TYPE: AdamW
    INIT_LEARNING_RATE: 0.00001
    MIN_LEARNING_RATE: 0.000001
    EPS: 0.000001
    BETAS: [0.9, 0.999]
    LR_MILESTONES: [250, 400]
  LOG_STEPS: 50
  ACCELERATOR: auto
  DEVICES: auto
  PRECISION: 32
  BEST_CHECKPOINT_BY: val_mAP
  COMPUTE_METRIC_AT_TRAIN_TIME: True
